#!/bin/bash
#SBATCH -A CS4380_5351_7332 # account name
#SBATCH -J p1_mis           # job name
#SBATCH -o p1_mis.%j        # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p normal           # queue name
#SBATCH -t 00:01:00         # expected maximum runtime (hh:mm:ss)

date

./mis /home1/00976/burtsche/Graphs/europe_osm.egr
./mis /home1/00976/burtsche/Graphs/kron_g500-logn21.egr
./mis /home1/00976/burtsche/Graphs/rgg_n_2_22_s0.egr
./mis /home1/00976/burtsche/Graphs/soc-LiveJournal1.egr
./mis /home1/00976/burtsche/Graphs/uk-2002.egr

date
