#!/bin/bash
#SBATCH -A CS4380_5351_7332 # account name
#SBATCH -J p1_vectoradd     # job name
#SBATCH -o p1_vectoradd.%j  # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p normal           # queue name
#SBATCH -t 00:01:00         # expected maximum runtime (hh:mm:ss)

date

./vectoradd 21000000
./vectoradd 210000000
./vectoradd 2100000000

date
